# Generated by Django 5.2.8 on 2026-01-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0002_partenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
