# Generated by Django 5.2.8 on 2026-01-19 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0003_alter_match_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='date_heure',
        ),
        migrations.AlterField(
            model_name='match',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_app.club'),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_domicile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_exterieur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
